:verbose: false
:concurrency: 3
:timeout: 25
:queues:
  - default
  - critical
  - high_priority
  - normal_priority
  - low_priority
staging:
  :concurrency: 3
production:
  :concurrency: 3
:schedule:
  update_chats_count:
    cron: '* 30 * * * *'   # Runs once per 30 minutes
    class: UpdateChatsCount
  update_messages_count:
    cron: '* 30 * * * *'   # Runs once per 30 minutes
    class: UpdateMessagesCount